#include<iostream>
#include<vector>
using namespace std;
int main(){
    // THERE ARE TWO TYPES OF MEMORY ONE IS STATIC AND OTHER ONE IS DYNAMIC IN STATIC MEMORY IT IS ALLOCATED AT COMPLIATION TIME MEANWHILE DYNAMIC MEMORY IS ALLOCATED AT RUNTIME,STATIC MEMORY IS STORED IN STACKS AND DYNAMAIC ONE IS HEAP,ARRAYS COME UNDER STATIC MEMORY ALLOCATION MEANWHILE VECTORS COME UNDER DYNAMIC MEMORY ALLOCATION THAT'S WHY THEIR SIZE CAN BE CHANGED.

    // MACHANISM OF MEMORY ALLOCATION TO A VECTOR : 
    // WHENEVER A NEW ELEMENT IS ADDED IN A VECTOR THEN IT GOES TO STORE IN SAME VECTOR BUT IF THE CAPACITY IS FULL THEN NEW VECTOR IS CREATED WITH 2X OF EXSISTING CAPACITY AND OLD VECTOR WILL BE DELETED AND NEW ONE WILL BE THE VECTOR.
    // THERE ARE TWO TERMS FOR A VECTOR SIZE AND CAPACITY.

    vector<int>v;
    v.push_back(1);
    v.push_back(2);
    v.push_back(3);
    v.push_back(1);
    v.push_back(1);
    cout<<"SIZE : "<<v.size()<<endl;
    cout<<"CAPACITY : "<<v.capacity()<<endl;
    return 0;
}